@baseUrl = http://localhost:36665
@auth = Authorization: Basic alice:


/odata/v4/
### ------------------------------------------------------------------------
# Get Service Document
GET {{baseUrl}}/cat


### ------------------------------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/cat/$metadata


### ------------------------------------------------------------------------
# Get all books with language en
GET {{baseUrl}}/cat/Books
Accept-Language: en


### ------------------------------------------------------------------------
# Get all books with language de
GET {{baseUrl}}/cat/Books
Accept-Language: de


### ------------------------------------------------------------------------
# Get all authors with language en
GET {{baseUrl}}/cat/Authors
Accept-Language: en


### ------------------------------------------------------------------------
# Get all authors with language de
GET {{baseUrl}}/cat/Authors
Accept-Language: de


### ------------------------------------------------------------------------
# Create a new author
POST {{baseUrl}}/cat/Authors
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}




### -------------------Before Phase-----------------------------------------------------
# Create a new author
POST {{baseUrl}}/odata/v4/admin/Authors
Content-Type: application/json

{
  "name": "Zriedrich Schiller",
  "dateOfBirth": "1959-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}

### ------------------After Phase------------------------------------------------------
# Get all books
GET {{baseUrl}}/cat/Books



### --------------------On Phase----------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/cat/$metadata



### ------------------------------------------------------------------------
# Retrieve the ID of the book with the title 'Faust'
# Use this ID to call the submitOrder action
# @name getBookID
GET {{baseUrl}}/cat/Books?$filter=title eq 'Faust'

###

@bookID = {{getBookID.response.body.$.value[0].ID}}

POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 2
}



### ------------------------------------------------------------------------
# Call the submitOrder action with a quantity of 0 -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 0
}


### -------------------------Queries-----------------------------------------------
# Call the submitOrder action with a quantity that exceeds stock -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 999999
}



### ------------------------------------------------------------------------
# Call the submitOrder action with an invalid book ID -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "quantity": 2
}